### ISSUE TITLE
More skins causes enigma2 crash

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#31]
When select universeHD skin (https://github.com/OpenVisionE2/UniverseHD-skin) and switch to it. It can be loaded up, it's really slow response, but if you want change skin again (Menu --> Setup --> GUI) when you select "Skin" then it crash

I would make issue at skin repository to not mess here, but issues there are disabled.

EDIT: seems this problem will have more skins, keep editing here to select wich ones

enigma2-plugin-skins-arctic-raed
enigma2-plugin-skins-openvix-iskin-dark
enigma2-plugin-skins-openvix-iskin-light
enigma2-plugin-skins-openvix-red-hd
enigma2-plugin-skins-openvix-youvix-blue
enigma2-plugin-skins-openvix-youvix-green
enigma2-plugin-skins-openvix-youvix-purple
enigma2-plugin-skins-openvix-youvix-red
enigma2-plugin-skins-universehd
enigma2-plugin-skins-slyk-1080-raed

```
<  3124.7336> 11:49:30.5914 2020-08-09 11:49:30+0200 [-] [skin] Processing screen 'SkinSelector', position=(0, 0), size=(1920 x 1080) for module 'SkinSelector'.
<  3124.7354> 11:49:30.5932 2020-08-09 11:49:30+0200 [-] [skin] Error in screen 'SkinSelector' widget 'widget' [Skin] {Arctic/skin.xml}: Component with name 'SkinList' was not found in skin of screen 'SkinSelector'!  Please contact the skin's author!!
```

```
<  2587.5254> 11:40:34.2556 2020-08-09 11:40:34+0200 [-] [InfoBarGenerics] KEY: 352 OK
<  2587.5262> 11:40:34.2564 2020-08-09 11:40:34+0200 [-] [ActionMap] Keymap 'OkCancelActions' -> Action = 'ok'.
<  2587.5323> 11:40:34.2625 2020-08-09 11:40:34+0200 [-] [ActionMap] removed duplicity: SetupActions ('right', 'Move to the next page')
<  2587.5332> 11:40:34.2634 2020-08-09 11:40:34+0200 [-] [ActionMap] removed duplicity: SetupActions ('left', 'Move to the previous page')
<  2587.5344> 11:40:34.2646 2020-08-09 11:40:34+0200 [-] [skin] Processing screen 'SkinSelector', position=(0, 0), size=(1920 x 1080) for module 'SkinSelector'.
<  2587.5425> 11:40:34.2727 2020-08-09 11:40:34+0200 [-] [skin] Error in screen 'SkinSelector' widget 'widget' [Skin] {UniverseHD/skin.xml}: Component with name 'SkinList' was not found in skin of screen 'SkinSelector'!  Please contact the skin's author!!
<  2587.5434> 11:40:34.2736 2020-08-09 11:40:34+0200 [-] [skin] Error in screen 'SkinSelector' widget 'widget' [Skin] {UniverseHD/skin.xml}: Component with name 'Preview' was not found in skin of screen 'SkinSelector'!  Please contact the skin's author!!
<  2587.5453> 11:40:34.2755 2020-08-09 11:40:34+0200 [-] [Screen] Warning: Skin is missing element 'preview' in <class 'Screens.SkinSelector.SkinSelector'>.
<  2587.5468> 11:40:34.2770 [gAccel] alloc failed
<  2587.5470> 11:40:34.2772 [gSurface] ERROR: accelAlloc failed
<  2587.5974> 11:40:34.3276 [gAccel] alloc failed
<  2587.5976> 11:40:34.3278 [gSurface] ERROR: accelAlloc failed
<  2587.6085> 11:40:34.3387 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/skin_default/skin.xml': 'PAL'.
<  2587.6097> 11:40:34.3399 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/PLi-FullHD/skin.xml': 'FHD'.
<  2587.6109> 11:40:34.3411 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/PLi-HD1/skin.xml': 'HD'.
<  2587.6118> 11:40:34.3420 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/OctEtFHD/skin.xml': 'FHD'.
<  2587.6127> 11:40:34.3429 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/UniverseHD/skin.xml': 'FHD'.
<  2587.6135> 11:40:34.3437 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/PLi-FullNightHD/skin.xml': 'FHD'.
<  2587.6146> 11:40:34.3448 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/MetrixHD/skin.xml': 'HD'.
<  2587.6159> 11:40:34.3461 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/PLi-HD/skin.xml': 'HD'.
<  2587.6171> 11:40:34.3473 2020-08-09 11:40:34+0200 [-] [SkinSelector] Resolution of skin '/usr/share/enigma2/PLi-HD2/skin.xml': 'HD'.
<  2587.6182> 11:40:34.3484 2020-08-09 11:40:34+0200 [-] Traceback (most recent call last):
<  2587.6188> 11:40:34.3490 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 79, in action
<  2587.6195> 11:40:34.3497 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 59, in action
<  2587.6201> 11:40:34.3503 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 162, in okbuttonClick
<  2587.6206> 11:40:34.3508 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 11, in __call__
<  2587.6212> 11:40:34.3514 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 175, in runScreen
<  2587.6218> 11:40:34.3519 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 181, in openDialog
<  2587.6223> 11:40:34.3525 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 363, in openWithCallback
<  2587.6230> 11:40:34.3532 2020-08-09 11:40:34+0200 [-]     dlg = self.open(screen, *arguments, **kwargs)
<  2587.6235> 11:40:34.3537 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 373, in open
<  2587.6243> 11:40:34.3545 2020-08-09 11:40:34+0200 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
<  2587.6248> 11:40:34.3550 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 310, in instantiateDialog
<  2587.6255> 11:40:34.3557 2020-08-09 11:40:34+0200 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
<  2587.6260> 11:40:34.3562 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 340, in doInstantiateDialog
<  2587.6267> 11:40:34.3569 2020-08-09 11:40:34+0200 [-]     dlg.applySkin()
<  2587.6272> 11:40:34.3574 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 241, in applySkin
<  2587.6277> 11:40:34.3579 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 272, in createGUIScreen
<  2587.6282> 11:40:34.3584 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 102, in layoutFinished
<  2587.6288> 11:40:34.3590 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 165, in refreshList
<  2587.6299> 11:40:34.3601 2020-08-09 11:40:34+0200 [-]   File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 169, in loadPreview
<  2587.6307> 11:40:34.3609 2020-08-09 11:40:34+0200 [-] TypeError: 'bool' object has no attribute '__getitem__'
<  2587.6310> 11:40:34.3612 [ePyObject] (CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap instance at 0xb014b378>>,('OkCancelActions', 'ok')) failed)
<  2591.5203> 11:40:38.2505 [gRC] main thread is non-idle! display spinner!
```

**Comment by petrkr** [comment]
This skin load skin list, but when you press press "OK" crash>>

Blue-HD:
```
<  3768.1479> 12:00:14.8738 2020-08-09 12:00:14+0200 [-] [ActionMap] Keymap 'SetupActions' -> Action = 'ok'.
<  3768.1485> 12:00:14.8743 2020-08-09 12:00:14+0200 [-] [SkinSelector] Selected skin: '/usr/share/enigma2/BundesligaFHD/skin.xml'
<  3768.1510> 12:00:14.8769 2020-08-09 12:00:14+0200 [-] [skin] Processing screen 'MessageBox', position=(380, 355), size=(520 x 10) for module 'MessageBox'.
libpng warning: iCCP: known incorrect sRGB profile
<  3768.1578> 12:00:14.8837 2020-08-09 12:00:14+0200 [-] [Screen] Warning: Skin is missing element 'WarningPixmap' in <class 'Screens.MessageBox.MessageBox'>(To save and apply the selected 'BundesligaFHD' skin the GUI needs to restart. Would you like to save the selection and restart the GUI now?).
<  3768.1586> 12:00:14.8845 2020-08-09 12:00:14+0200 [-] [Screen] Warning: Skin is missing element 'autoresize' in <class 'Screens.MessageBox.MessageBox'>(To save and apply the selected 'BundesligaFHD' skin the GUI needs to restart. Would you like to save the selection and restart the GUI now?).
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
<  3768.1635> 12:00:14.8894 2020-08-09 12:00:14+0200 [-] Traceback (most recent call last):
<  3768.1642> 12:00:14.8900 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 79, in action
<  3768.1649> 12:00:14.8907 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 59, in action
<  3768.1654> 12:00:14.8913 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 202, in save
<  3768.1661> 12:00:14.8919 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 363, in openWithCallback
<  3768.1668> 12:00:14.8926 2020-08-09 12:00:14+0200 [-]     dlg = self.open(screen, *arguments, **kwargs)
<  3768.1673> 12:00:14.8931 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 373, in open
<  3768.1679> 12:00:14.8938 2020-08-09 12:00:14+0200 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
<  3768.1684> 12:00:14.8942 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 310, in instantiateDialog
<  3768.1690> 12:00:14.8949 2020-08-09 12:00:14+0200 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
<  3768.1694> 12:00:14.8953 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 340, in doInstantiateDialog
<  3768.1701> 12:00:14.8959 2020-08-09 12:00:14+0200 [-]     dlg.applySkin()
<  3768.1705> 12:00:14.8964 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 241, in applySkin
<  3768.1724> 12:00:14.8982 2020-08-09 12:00:14+0200 [-]   File "/usr/lib/enigma2/python/Screens/Screen.py", line 269, in createGUIScreen
<  3768.1731> 12:00:14.8989 2020-08-09 12:00:14+0200 [-]   File "skin applet", line 1, in <module>
<  3768.1738> 12:00:14.8997 2020-08-09 12:00:14+0200 [-] AttributeError: 'MessageBox' object has no attribute 'autoResize'
<  3768.1740> 12:00:14.8999 [ePyObject] (CallObject(<bound method HelpableNumberActionMap.action of <Components.ActionMap.HelpableNumberActionMap instance at 0xb0ca76c0>>,('SetupActions', 'ok')) failed)
```

**Comment by petrkr** [comment]
This skin missing menu at all

enigma2-plugin-skins-openvix-vixbmc-1080-bello


```
< 12554.3137> 14:26:40.0863 2020-08-09 14:26:40+0200 [-] [skin] Processing screen 'Menu' from list 'menu_mainmenu, Menu', position=(0, 0), size=(1920 x 1080) for module 'MainMenu'.
< 12554.3289> 14:26:40.1015 2020-08-09 14:26:40+0200 [-] [skin] Error in screen 'Menu' 'Is576'!
< 12554.3346> 14:26:40.1073 2020-08-09 14:26:40+0200 [-] [skin] Error: [Skin] {ViXBMC_1080_Bello/skin.xml}: Color 'window-bg' must be #aarrggbb or valid named color!  Please contact the skin's author!
< 12554.3363> 14:26:40.1089 2020-08-09 14:26:40+0200 [-] [skin] Processing screen 'MenuSummary', position=(0, 0), size=(1 x 1) for module 'MenuSummary'.

```

**Comment by persianpros** [comment]
I will remove vix skins from our feeds as they're not for our enigma2

**Comment by petrkr** [comment]
Finished.

those skins are working
```
enigma2-plugin-skins-atilehd-raed - git57+1902500-r0
enigma2-plugin-skins-blacktransfhd-raed - git57+1902500-r0
enigma2-plugin-skins-bundesligafhd-raed - git57+1902500-r0
enigma2-plugin-skins-cinogripli - 1.0+git14+5a8d2c9-r0
enigma2-plugin-skins-glamouraurafhd - 1.0+git528+69bc8c9-r0
enigma2-plugin-skins-hdlinesuper-raed - git57+1902500-r0
enigma2-plugin-skins-iflatfhd - git24+80ed514-r0
enigma2-plugin-skins-magic - 1.2+git331+8b5fb84-r0
enigma2-plugin-skins-maxfhdxta-raed - git57+1902500-r0
enigma2-plugin-skins-metrix-vision - 2.2+git2031+9fba9ab-r0
enigma2-plugin-skins-multibox-raed - git57+1902500-r0
enigma2-plugin-skins-mx-hq7 - 1.0+git4+cfdda15-r0
enigma2-plugin-skins-mx-hq9w - 1.0+git28+3a24441-r0
enigma2-plugin-skins-mxblack-raed - git57+1902500-r0
enigma2-plugin-skins-mxhq9b-raed - git57+1902500-r0
enigma2-plugin-skins-mxsline-raed - git57+1902500-r0
enigma2-plugin-skins-octetfhd - git117+933c5c3-r0
enigma2-plugin-skins-openvix - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-halo - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-magic-fhd - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-meta - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-mhd-common - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-pli-hd-night - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-simple-ten-eighty - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-vix-common - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-vixbmc-1080 - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-vixbmc-1080-common - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-vixbmc-hd-common - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-vixbmc-hd-night - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-vixbmc-hd-slim - git2337+5ae754c-r0
enigma2-plugin-skins-openvix-vixbmc-metropolis - git2337+5ae754c-r0
enigma2-plugin-skins-pli-hd - 0.1+git2128+0f059bf-r0
enigma2-plugin-skins-pli-hd-fullnight - 0.1+git107+3c271e8-r0
enigma2-plugin-skins-simple-gray-hd - 1.0+git162+3ec4bd4-r0
enigma2-plugin-skins-turbo-raed - git57+1902500-r0
enigma2-plugin-skins-whitetransfhd-raed - git57+1902500-r0
enigma2-plugin-skins-wowcataclysmfhd-raed - git57+1902500-r0
```

Rest are in three categories of problems, edit should be done already

**Comment by fairbird** [comment]
universeHD not compatible our images (No body edit it yet)

**Comment by petrkr** [comment]
How looks this ?
Will we edit those skins or remove them?
