### ISSUE TITLE
can not compile after latest commits

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#52]
latest working (which I've tried) was from Sep 7th

now can not compile rclone package, tried also remove build directory and do fresh:

```
| # github.com/rclone/rclone
| panic: runtime error: invalid memory address or nil pointer dereference
| [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51d95b]
```

```
| goroutine 1 [running]:
| cmd/link/internal/loader.(*Loader).FuncInfo(0xc0000b0000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
| 	/home/builder/openvision-development-platform/build/tmp/work/x86_64-linux/go-cross-cortexa15hf-neon-vfpv4/1.15.1-r0/recipe-sysroot-native/usr/lib/arm-oe-linux-gnueabi/go/src/cmd/link/internal/loader/loader.go:1900 +0x9b
| cmd/link/internal/ld.(*stkChk).check(0xc00013ee78, 0xc00013eb58, 0x2, 0x0)
| 	/home/builder/openvision-development-platform/build/tmp/work/x86_64-linux/go-cross-cortexa15hf-neon-vfpv4/1.15.1-r0/recipe-sysroot-native/usr/lib/arm-oe-linux-gnueabi/go/src/cmd/link/internal/ld/lib.go:2362 +0x130
| cmd/link/internal/ld.(*stkChk).check(0xc00013ee78, 0xc00013ed08, 0x1, 0x0)
| 	/home/builder/openvision-development-platform/build/tmp/work/x86_64-linux/go-cross-cortexa15hf-neon-vfpv4/1.15.1-r0/recipe-sysroot-native/usr/lib/arm-oe-linux-gnueabi/go/src/cmd/link/internal/ld/lib.go:2421 +0x585
| cmd/link/internal/ld.(*stkChk).check(0xc00013ee78, 0xc00013ee60, 0x0, 0xffffffffffffffff)
| 	/home/builder/openvision-development-platform/build/tmp/work/x86_64-linux/go-cross-cortexa15hf-neon-vfpv4/1.15.1-r0/recipe-sysroot-native/usr/lib/arm-oe-linux-gnueabi/go/src/cmd/link/internal/ld/lib.go:2421 +0x585
| cmd/link/internal/ld.(*Link).dostkcheck(0xc000115880)
| 	/home/builder/openvision-development-platform/build/tmp/work/x86_64-linux/go-cross-cortexa15hf-neon-vfpv4/1.15.1-r0/recipe-sysroot-native/usr/lib/arm-oe-linux-gnueabi/go/src/cmd/link/internal/ld/lib.go:2322 +0x2bc
| cmd/link/internal/ld.Main(0x87f940, 0x4, 0x8, 0x1, 0xd, 0xe, 0x0, 0x0, 0x6d54da, 0x12, ...)
| 	/home/builder/openvision-development-platform/build/tmp/work/x86_64-linux/go-cross-cortexa15hf-neon-vfpv4/1.15.1-r0/recipe-sysroot-native/usr/lib/arm-oe-linux-gnueabi/go/src/cmd/link/internal/ld/main.go:254 +0xe65
| main.main()
| 	/home/builder/openvision-development-platform/build/tmp/work/x86_64-linux/go-cross-cortexa15hf-neon-vfpv4/1.15.1-r0/recipe-sysroot-native/usr/lib/arm-oe-linux-gnueabi/go/src/cmd/link/main.go:68 +0x1dc
| # github.com/rclone/rclone/fstest/test_all
| panic: runtime error: invalid memory address or nil pointer dereference
| [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51d95b]
```

**Comment by persianpros** [comment]
Yep confirmed, happens with feeds and probably related to "go" upgrade on OE.

**Comment by petrkr** [comment]
Maybe report this to https://github.com/rclone/rclone ? You updated new go version? So some incompatible with new version?

**Comment by persianpros** [comment]
I just upgraded our OE to latest version of https://github.com/openembedded (master branch) so lots of packages upgraded and "go" was one of them.

@Hains removed it from our feeds for now: https://github.com/OpenVisionE2/openvision-development-platform/commit/3c3fb9ae1dc65d119b9dc6739402a996e33de37b

But as far as I saw rclone isn't a compatible package and over time we had problems with it, so if we don't need it as a pre-installable package I vote to remove it from our feeds.

I don't have time to work on rclone for now, sorry.

**Comment by petrkr** [comment]
Yes agree, I think it's low-prio package, question was about report bug directly to rclone team.

**Comment by persianpros** [comment]
@petrkr 

I know you're so good at finding problems and debugging things, please check https://travis-ci.org/github/OpenVisionE2/enigma2-openvision/builds/726183419?utm_source=github_status&utm_medium=notification or any other Travis builds in our enigma2 and help me with getting rid of warnings.

Seems some parts of our enigma2 are using deprecated things so it's time to follow the new GCC suggestions as we're using GCC 10.2 now :+1:

**Comment by petrkr** [comment]
So closing solution is 'removed from feed'?

**Comment by persianpros** [comment]
@petrkr 

No, I will work on rclone in this week ;)
