### ISSUE TITLE
Error build python-setup, rpm native

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#62]
Something gets wrong on latest branch

```
ERROR: python3-setuptools-native-45.2.0-r0 do_compile: 'python3 setup.py build ' execution failed.
ERROR: python3-setuptools-native-45.2.0-r0 do_compile: Execution of '/src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650' failed with exit code 1:
/src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650: 115: /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650: /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/recipe-sysroot-native/usr/bin/python3-native/python3: Permission denied
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/log.do_compile.8650
Log data follows:
| DEBUG: Executing shell function do_compile
| /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650: 115: /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650: /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/recipe-sysroot-native/usr/bin/python3-native/python3: Permission denied
| ERROR: 'python3 setup.py build ' execution failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650' failed with exit code 1:
| /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650: 115: /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/temp/run.do_compile.8650: /src/build/tmp/work/x86_64-linux/python3-setuptools-native/45.2.0-r0/recipe-sysroot-native/usr/bin/python3-native/python3: Permission denied
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (virtual:native:/src/openembedded-core/meta/recipes-devtools/python/python3-setuptools_45.2.0.bb:do_compile) failed with exit code '1'
ERROR: libxml2-native-2.9.10-r0 do_configure: Execution of '/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/temp/run.do_configure.8657' failed with exit code 1:
automake (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.                                                                                                                   

Written by Tom Tromey <tromey@redhat.com>                                                                                                                               
       and Alexandre Duret-Lutz <adl@gnu.org>.                                                                                                                          
AUTOV is 1.16                                                                                                                                                           
autoreconf: Entering directory `.'                                                                                                                                      
autoreconf: configure.ac: not using Gettext                                                                                                                             
autoreconf: running: aclocal --system-acdir=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/share/aclocal/ --automake-acdir=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/share/aclocal-1.16 -I /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/ -I /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/m4/ --force -I m4                                                                       
autoreconf: configure.ac: tracing                                                                                                                                       
autoreconf: running: libtoolize --copy --force                                                                                                                          
libtoolize: putting auxiliary files in '.'.                                                                                                                             
libtoolize: copying file './ltmain.sh'                                                                                                                                  
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.                                                                                                               
libtoolize: copying file 'm4/libtool.m4'                                                                                                                                
libtoolize: copying file 'm4/ltoptions.m4'                                                                                                                              
libtoolize: copying file 'm4/ltsugar.m4'                                                                                                                                
libtoolize: copying file 'm4/ltversion.m4'                                                                                                                              
libtoolize: copying file 'm4/lt~obsolete.m4'                                                                                                                            
autoreconf: running: /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/bin/autoconf --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/ --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/m4/ --force                                        
autoreconf: running: /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/bin/autoheader --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/ --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/m4/ --force                                      
autoreconf: running: automake --add-missing --copy --force-missing                                                                                                      
configure.ac:53: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:                                                         
configure.ac:53: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation                                               
configure.ac:61: installing './compile'                                                                                                                                 
configure.ac:53: installing './missing'                                                                                                                                 
Makefile.am: installing './depcomp'                                                                                                                                     
doc/Makefile.am:21: warning: wildcard tutorial/*.html: non-POSIX variable name                                                                                          
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard tutorial/*.c: non-POSIX variable name                                                                                             
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard tutorial/*.pdf: non-POSIX variable name                                                                                           
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard tutorial/images/*.png: non-POSIX variable name                                                                                    
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard tutorial/images/callouts/*.png: non-POSIX variable name                                                                           
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard API*.html: non-POSIX variable name                                                                                                
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard *.1: non-POSIX variable name                                                                                                      
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard *.xsl: non-POSIX variable name                                                                                                    
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard *.html: non-POSIX variable name                                                                                                   
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard *.gif: non-POSIX variable name                                                                                                    
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard html/*.html: non-POSIX variable name                                                                                              
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:21: warning: wildcard html/*.png: non-POSIX variable name                                                                                               
doc/Makefile.am:21: (probably a GNU make extension)                                                                                                                     
doc/Makefile.am:300: warning: filter-out %/xmlversion.h, $(wildcard $(top_srcdir: non-POSIX variable name                                                               
doc/Makefile.am:300: (probably a GNU make extension)                                                                                                                    
doc/Makefile.am:300: warning: wildcard $(top_srcdir: non-POSIX variable name                                                                                            
doc/Makefile.am:300: (probably a GNU make extension)                                                                                                                    
autoreconf: running: gnu-configize                                                                                                                                      
autoreconf: Leaving directory `.'                                                                                                                                       
Failed to import the site module                                                                                                                                        
Traceback (most recent call last):                                                                                                                                      
  File "/usr/lib/python3.6/site.py", line 570, in <module>                                                                                                              
    main()                                                                                                                                                              
  File "/usr/lib/python3.6/site.py", line 556, in main                                                                                                                  
    known_paths = addusersitepackages(known_paths)                                                                                                                      
  File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages                                                                                                   
    user_site = getusersitepackages()                                                                                                                                   
  File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages                                                                                                   
    user_base = getuserbase() # this will also set USER_BASE                                                                                                            
  File "/usr/lib/python3.6/site.py", line 254, in getuserbase                                                                                                           
    USER_BASE = get_config_var('userbase')                                                                                                                              
  File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var                                                                                                   
    return get_config_vars().get(name)                                                                                                                                  
  File "/usr/lib/python3.6/sysconfig.py", line 550, in get_config_vars                                                                                                  
    _init_posix(_CONFIG_VARS)                                                                                                                                           
  File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix                                                                                                      
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)                                                                                               
ModuleNotFoundError: No module named '_sysconfigdata'                                                                                                                   
WARNING: exit code 1 from a shell command.                                                                                                                              

ERROR: Logfile of failure stored in: /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/temp/log.do_configure.8657
```

```
| autoreconf: running: gnu-configize
| autoreconf: Leaving directory `.'
| Failed to import the site module
| Traceback (most recent call last):
|   File "/usr/lib/python3.6/site.py", line 570, in <module>
|     main()
|   File "/usr/lib/python3.6/site.py", line 556, in main
|     known_paths = addusersitepackages(known_paths)
|   File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages
|     user_site = getusersitepackages()
|   File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages
|     user_base = getuserbase() # this will also set USER_BASE
|   File "/usr/lib/python3.6/site.py", line 254, in getuserbase
|     USER_BASE = get_config_var('userbase')
|   File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var
|     return get_config_vars().get(name)
|   File "/usr/lib/python3.6/sysconfig.py", line 550, in get_config_vars
|     _init_posix(_CONFIG_VARS)
|   File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix
|     _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
| ModuleNotFoundError: No module named '_sysconfigdata'
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/temp/run.do_configure.8657' failed with exit code 1:
| automake (GNU automake) 1.16.1
| Copyright (C) 2018 Free Software Foundation, Inc.
| License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
| This is free software: you are free to change and redistribute it.
| There is NO WARRANTY, to the extent permitted by law.
| 
| Written by Tom Tromey <tromey@redhat.com>
|        and Alexandre Duret-Lutz <adl@gnu.org>.
| AUTOV is 1.16
| autoreconf: Entering directory `.'
| autoreconf: configure.ac: not using Gettext
| autoreconf: running: aclocal --system-acdir=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/share/aclocal/ --automake-acdir=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/share/aclocal-1.16 -I /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/ -I /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/m4/ --force -I m4
| autoreconf: configure.ac: tracing
| autoreconf: running: libtoolize --copy --force
| libtoolize: putting auxiliary files in '.'.
| libtoolize: copying file './ltmain.sh'
| libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
| libtoolize: copying file 'm4/libtool.m4'
| libtoolize: copying file 'm4/ltoptions.m4'
| libtoolize: copying file 'm4/ltsugar.m4'
| libtoolize: copying file 'm4/ltversion.m4'
| libtoolize: copying file 'm4/lt~obsolete.m4'
| autoreconf: running: /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/bin/autoconf --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/ --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/m4/ --force
| autoreconf: running: /src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/recipe-sysroot-native/usr/bin/autoheader --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/ --include=/src/build/tmp/work/x86_64-linux/libxml2-native/2.9.10-r0/libxml2-2.9.10/m4/ --force
| autoreconf: running: automake --add-missing --copy --force-missing
| configure.ac:53: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
| configure.ac:53: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
| configure.ac:61: installing './compile'
| configure.ac:53: installing './missing'
| Makefile.am: installing './depcomp'
| doc/Makefile.am:21: warning: wildcard tutorial/*.html: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard tutorial/*.c: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard tutorial/*.pdf: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard tutorial/images/*.png: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard tutorial/images/callouts/*.png: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard API*.html: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard *.1: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard *.xsl: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard *.html: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard *.gif: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard html/*.html: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:21: warning: wildcard html/*.png: non-POSIX variable name
| doc/Makefile.am:21: (probably a GNU make extension)
| doc/Makefile.am:300: warning: filter-out %/xmlversion.h, $(wildcard $(top_srcdir: non-POSIX variable name
| doc/Makefile.am:300: (probably a GNU make extension)
| doc/Makefile.am:300: warning: wildcard $(top_srcdir: non-POSIX variable name
| doc/Makefile.am:300: (probably a GNU make extension)
| autoreconf: running: gnu-configize
| autoreconf: Leaving directory `.'
| Failed to import the site module
| Traceback (most recent call last):
|   File "/usr/lib/python3.6/site.py", line 570, in <module>
|     main()
|   File "/usr/lib/python3.6/site.py", line 556, in main
|     known_paths = addusersitepackages(known_paths)
|   File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages
|     user_site = getusersitepackages()
|   File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages
|     user_base = getuserbase() # this will also set USER_BASE
|   File "/usr/lib/python3.6/site.py", line 254, in getuserbase
|     USER_BASE = get_config_var('userbase')
|   File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var
|     return get_config_vars().get(name)
|   File "/usr/lib/python3.6/sysconfig.py", line 550, in get_config_vars
|     _init_posix(_CONFIG_VARS)
|   File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix
|     _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
| ModuleNotFoundError: No module named '_sysconfigdata'
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (virtual:native:/src/openembedded-core/meta/recipes-core/libxml/libxml2_2.9.10.bb:do_configure) failed with exit code '1'
ERROR: rpm-native-1_4.14.2.1-r0 do_configure: Execution of '/src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/temp/run.do_configure.8645' failed with exit code 1:
automake (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.                                                                                                                       
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>                                                                                      
This is free software: you are free to change and redistribute it.                                                                                                      
There is NO WARRANTY, to the extent permitted by law.                                                                                                                   

Written by Tom Tromey <tromey@redhat.com>                                                                                                                               
       and Alexandre Duret-Lutz <adl@gnu.org>.                                                                                                                          
AUTOV is 1.16                                                                                                                                                           
autoreconf: Entering directory `.'                                                                                                                                      
autoreconf: running: aclocal --system-acdir=/src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/share/aclocal/ --automake-acdir=/src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/share/aclocal-1.16 -I /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/git/m4/ --force -I m4                                                                                                                                                               
autoreconf: configure.ac: tracing                                                                                                                                       
autoreconf: configure.ac: adding subdirectory db3 to autoreconf                                                                                                         
autoreconf: Entering directory `db3'                                                                                                                                    
autoreconf: configure.ac: not using Autoconf                                                                                                                            
autoreconf: Leaving directory `db3'                                                                                                                                     
autoreconf: running: libtoolize --copy --force                                                                                                                          
libtoolize: putting auxiliary files in '.'.                                                                                                                             
libtoolize: copying file './ltmain.sh'                                                                                                                                  
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.                                                                                                               
libtoolize: copying file 'm4/libtool.m4'                                                                                                                                
libtoolize: copying file 'm4/ltoptions.m4'                                                                                                                              
libtoolize: copying file 'm4/ltsugar.m4'                                                                                                                                
libtoolize: copying file 'm4/ltversion.m4'                                                                                                                              
libtoolize: copying file 'm4/lt~obsolete.m4'                                                                                                                            
autoreconf: running: /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/bin/autoconf --include=/src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/git/m4/ --force                                                                                                                                       
autoreconf: running: /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/bin/autoheader --include=/src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/git/m4/ --force                                                                                                                                     
autoreconf: running: automake --add-missing --copy --force-missing                                                                                                      
configure.ac:14: installing './compile'                                                                                                                                 
configure.ac:8: installing './missing'                                                                                                                                  
Makefile.am: installing './depcomp'                                                                                                                                     
autoreconf: Leaving directory `.'                                                                                                                                       
Failed to import the site module                                                                                                                                        
Traceback (most recent call last):                                                                                                                                      
  File "/usr/lib/python3.6/site.py", line 570, in <module>                                                                                                              
    main()                                                                                                                                                              
  File "/usr/lib/python3.6/site.py", line 556, in main                                                                                                                  
    known_paths = addusersitepackages(known_paths)                                                                                                                      
  File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages                                                                                                   
    user_site = getusersitepackages()                                                                                                                                   
  File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages                                                                                                   
    user_base = getuserbase() # this will also set USER_BASE                                                                                                            
  File "/usr/lib/python3.6/site.py", line 254, in getuserbase                                                                                                           
    USER_BASE = get_config_var('userbase')                                                                                                                              
  File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var                                                                                                   
    return get_config_vars().get(name)                                                                                                                                  
  File "/usr/lib/python3.6/sysconfig.py", line 550, in get_config_vars                                                                                                  
    _init_posix(_CONFIG_VARS)                                                                                                                                           
  File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix                                                                                                      
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)                                                                                               
ModuleNotFoundError: No module named '_sysconfigdata'                                                                                                                   
WARNING: exit code 1 from a shell command.                                                                                                                              

ERROR: Logfile of failure stored in: /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/temp/log.do_configure.8645
```

why it compile RPM ?

**Comment by petrkr** [comment]
Seems it will be connected with build in Docker version of ubuntu. I will try to solve that. If someone know something what could help me. Please keep posted

**Comment by petrkr** [comment]
it generates wrong enviroment variable `_PYTHON_SYSCONFIGDATA_NAME` as `_sysconfigdata` instead `_sysconfigdata_m_linux_x86_64-linux-gnu`

`builder@9156f39de1ba:/src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/temp$ vi run.do_configure`
```
export _PYTHON_SYSCONFIGDATA_NAME="_sysconfigdata"
export _PYTHON_SYSCONFIGDATA_NAME="_sysconfigdata_m_linux_x86_64-linux-gnu"
```

**Comment by petrkr** [comment]
Why it configure by system-wide python instead build-root one?

```
checking whether /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 version is >= 2.6... no
configure: error: Python interpreter is too old
```

```
builder@9156f39de1ba:/src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/temp$ /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
bash: /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/bin/python3-native/python3: Permission denied
```


OK it this could be fixed by `chmod +x /src/build/tmp/work/x86_64-linux/rpm-native/1_4.14.2.1-r0/recipe-sysroot-native/usr/bin/python3-native/python3`

because it missing executable, so it used system-wide python3 instead build-root one.

Now figure out why

**Comment by petrkr** [comment]
Fixed by https://github.com/petrkr/openvision-development-platform/commit/f70a7726fc089ba1c6db6d0776af1fa70688e06e
