### ISSUE TITLE
MaxyTec ERROR bitbake/lib/bb/pysh/pyshlex

### ISSUE THREAD

**Issue by atefganm** [OpenVisionE2/openvision-development-platform#97]
`
Compiling multibox image, please wait ...

Generating /home/atef/openvision-development-platform/build/conf/openvision.conf
Generating /home/atef/openvision-development-platform/build/conf/local.conf
Building image for multibox
WARNING: Layer meta-openvision-layer should set LAYERSERIES_COMPAT_meta-openvision-layer in its conf/layer.conf file to list the core layer names it is compatible with.
Loading cache: 100% |                                                                                                                                                                              | ETA:  --:--:--
Loaded 0 entries from dependency cache.
NOTE: /home/atef/openvision-development-platform/meta-openvision/recipes-core/glibc/glibc-initial_2.25.bb: glibc-initial doesn't build cleanly with -Os, adding -Wno-error to SELECTED_OPTIMIZATION| ETA:  --:--:--
NOTE: /home/atef/openvision-development-platform/meta-openvision/recipes-core/glibc/glibc-initial_2.25.bb: nativesdk-glibc-initial doesn't build cleanly with -Os, adding -Wno-error to SELECTED_OPTIMIZATION:01:50
ERROR: /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-image.bb: Error during parse shell code, the last 5 lines are:                               | ETA:  0:01:33
    mcopy -i /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/bootoptions.img -v /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/STARTUP_RECOVERY ::
    mcopy -i /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/bootoptions.img -v /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/bootmenu.conf ::
    cp -f /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/bootoptions.img /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/deploy-openvision-image-image-complete/bootoptions.img
 	mkdir -p /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox; 	cp -f /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/deploy-openvision-image-image-complete/bootoptions.img /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/bootoptions.img; 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/update_bootargs_multibox.bin /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/update_bootargs_multibox.bin; 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/multibox/fastboot.bin /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/fastboot.bin; 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/multibox/bootargs-8gb.bin /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/bootargs.bin; 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/multibox/pq_param.bin /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/pq_param.bin; 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/multibox/baseparam.img /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/baseparam.img; 	if [ -e /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/multibox/recovery.bin ]; then 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/multibox/recovery.bin /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/recovery.bin; 	fi; 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/maxytec-partitions-multibox/multibox/logo.img /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/logo.img; 	echo "multibox-20201224-RECOVERY" > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/multibox/recoveryversion; 	echo "***** ATTENTION *****" >/home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/recovery_multibox_READ.ME; 	echo "This RECOVERY only need when you have issue access the MULTIBOOT MENU" >>/home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/recovery_multibox_READ.ME; 	echo "The openvision-develop-extralanguage-python2-10.2-r312-multibox_recovery_emmc.zip should been install normally once (or if there is an update.)" >>/home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/recovery_multibox_READ.ME; 	echo "This is needed for avoid images conflicts as the partition layout (bootargs) is of huge essential." >>/home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/recovery_multibox_READ.ME; echo "A small change can destroy all your install images. So we can better leave it and not install it if it's not need." >>/home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery/recovery_multibox_READ.ME; 	rm -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/*.zip; 	cd /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery ; 	zip -r ../openvision-develop-extralanguage-python2-10.2-r312-multibox_recovery_emmc.zip *; 	rm -Rf /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox-recovery; 	mkdir -p /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox; 	cp -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/uImage /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/uImage; 	tar -cvf /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/rootfs.tar -C /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/rootfs .; 	mv -f /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/rootfs.tar /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/rootfs.tar; 	bzip2 /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/rootfs.tar; 	echo "openvision-develop-extralanguage-python2-10.2-r312-multibox" > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/imageversion; 	echo "https://forum.openvision.tech/app.php/donate" > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/${MACHINE/multibox/donate.txt; 	echo "openvision-develop-extralanguage-python2-10.2-r312-multibox_usb.zip" > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/unforce_multibox.txt; 	echo "Rename the unforce_multibox.txt to force_multibox.txt and move it to the root of your usb-stick" > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/force_multibox_READ.ME; 	echo "When you enter the recovery menu then it will force to install the image openvision-develop-extralanguage-python2-10.2-r312-multibox_usb.zip in the linux1 selection" >> /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/force_multibox_READ.ME; 	cd /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox; 	zip -r ../openvision-develop-extralanguage-python2-10.2-r312-multibox_usb.zip *; 	cd ..; 	rm -Rf /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox; 	
	cd /home/atef/openvision-development-platform/build/tmp/work/multibox-oe-linux-gnueabi/openvision-image/1.0-r0/deploy-openvision-image-image-complete
WARNING: /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-image.bb: Exception during build_dependencies for do_image_maxytecfastboot8gb
WARNING: /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-image.bb: Error during finalise of /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-image.bb
ERROR: Unable to parse /home/atef/openvision-development-platform/meta-openvision/recipes-openvision/images/openvision-image.bb
Traceback (most recent call last):
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/pysh/pyshlex.py", line 688, in PLYLexer._parse_quoted(eof=True):
                 
    >        wtree, remaining = self._wordlexer.add(input, eof)
             self._wordlexer = None
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/pysh/pyshlex.py", line 146, in WordLexer.add(data=['$', '{', 'M', 'A', 'C', 'H', 'I', 'N', 'E', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'd', 'o', 'n', 'a', 't', 'e', '.', 't', 'x', 't', ';', ' ', '\t', 'e', 'c', 'h', 'o', ' ', '"', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', '-', 'e', 'x', 't', 'r', 'a', 'l', 'a', 'n', 'g', 'u', 'a', 'g', 'e', '-', 'p', 'y', 't', 'h', 'o', 'n', '2', '-', '1', '0', '.', '2', '-', 'r', '3', '1', '2', '-', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'u', 's', 'b', '.', 'z', 'i', 'p', '"', ' ', '>', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'u', 'n', 'f', 'o', 'r', 'c', 'e', '_', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '.', 't', 'x', 't', ';', ' ', '\t', 'e', 'c', 'h', 'o', ' ', '"', 'R', 'e', 'n', 'a', 'm', 'e', ' ', 't', 'h', 'e', ' ', 'u', 'n', 'f', 'o', 'r', 'c', 'e', '_', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '.', 't', 'x', 't', ' ', 't', 'o', ' ', 'f', 'o', 'r', 'c', 'e', '_', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '.', 't', 'x', 't', ' ', 'a', 'n', 'd', ' ', 'm', 'o', 'v', 'e', ' ', 'i', 't', ' ', 't', 'o', ' ', 't', 'h', 'e', ' ', 'r', 'o', 'o', 't', ' ', 'o', 'f', ' ', 'y', 'o', 'u', 'r', ' ', 'u', 's', 'b', '-', 's', 't', 'i', 'c', 'k', '"', ' ', '>', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'f', 'o', 'r', 'c', 'e', '_', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'R', 'E', 'A', 'D', '.', 'M', 'E', ';', ' ', '\t', 'e', 'c', 'h', 'o', ' ', '"', 'W', 'h', 'e', 'n', ' ', 'y', 'o', 'u', ' ', 'e', 'n', 't', 'e', 'r', ' ', 't', 'h', 'e', ' ', 'r', 'e', 'c', 'o', 'v', 'e', 'r', 'y', ' ', 'm', 'e', 'n', 'u', ' ', 't', 'h', 'e', 'n', ' ', 'i', 't', ' ', 'w', 'i', 'l', 'l', ' ', 'f', 'o', 'r', 'c', 'e', ' ', 't', 'o', ' ', 'i', 'n', 's', 't', 'a', 'l', 'l', ' ', 't', 'h', 'e', ' ', 'i', 'm', 'a', 'g', 'e', ' ', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', '-', 'e', 'x', 't', 'r', 'a', 'l', 'a', 'n', 'g', 'u', 'a', 'g', 'e', '-', 'p', 'y', 't', 'h', 'o', 'n', '2', '-', '1', '0', '.', '2', '-', 'r', '3', '1', '2', '-', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'u', 's', 'b', '.', 'z', 'i', 'p', ' ', 'i', 'n', ' ', 't', 'h', 'e', ' ', 'l', 'i', 'n', 'u', 'x', '1', ' ', 's', 'e', 'l', 'e', 'c', 't', 'i', 'o', 'n', '"', ' ', '>', '>', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'f', 'o', 'r', 'c', 'e', '_', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'R', 'E', 'A', 'D', '.', 'M', 'E', ';', ' ', '\t', 'c', 'd', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', ';', ' ', '\t', 'z', 'i', 'p', ' ', '-', 'r', ' ', '.', '.', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', '-', 'e', 'x', 't', 'r', 'a', 'l', 'a', 'n', 'g', 'u', 'a', 'g', 'e', '-', 'p', 'y', 't', 'h', 'o', 'n', '2', '-', '1', '0', '.', '2', '-', 'r', '3', '1', '2', '-', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'u', 's', 'b', '.', 'z', 'i', 'p', ' ', '*', ';', ' ', '\t', 'c', 'd', ' ', '.', '.', ';', ' ', '\t', 'r', 'm', ' ', '-', 'R', 'f', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', ';', ' ', '\t', '\n', '\t', 'c', 'd', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'w', 'o', 'r', 'k', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '-', 'o', 'e', '-', 'l', 'i', 'n', 'u', 'x', '-', 'g', 'n', 'u', 'e', 'a', 'b', 'i', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'i', 'm', 'a', 'g', 'e', '/', '1', '.', '0', '-', 'r', '0', '/', 'd', 'e', 'p', 'l', 'o', 'y', '-', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'i', 'm', 'a', 'g', 'e', '-', 'i', 'm', 'a', 'g', 'e', '-', 'c', 'o', 'm', 'p', 'l', 'e', 't', 'e'], eof=True):
             self._buffer += list(data)
    >        self._parse(eof)
             
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/pysh/pyshlex.py", line 324, in WordLexer._parse(eof=True):
                     
    >            read, closed = parsefunc(buf, result, eof)
                     
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/pysh/pyshlex.py", line 292, in WordLexer._parse_dollar(buf=[' ', '>', '>', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'f', 'o', 'r', 'c', 'e', '_', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'R', 'E', 'A', 'D', '.', 'M', 'E', ';', ' ', '\t', 'c', 'd', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', ';', ' ', '\t', 'z', 'i', 'p', ' ', '-', 'r', ' ', '.', '.', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', '-', 'e', 'x', 't', 'r', 'a', 'l', 'a', 'n', 'g', 'u', 'a', 'g', 'e', '-', 'p', 'y', 't', 'h', 'o', 'n', '2', '-', '1', '0', '.', '2', '-', 'r', '3', '1', '2', '-', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'u', 's', 'b', '.', 'z', 'i', 'p', ' ', '*', ';', ' ', '\t', 'c', 'd', ' ', '.', '.', ';', ' ', '\t', 'r', 'm', ' ', '-', 'R', 'f', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', ';', ' ', '\t', '\n', '\t', 'c', 'd', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'w', 'o', 'r', 'k', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '-', 'o', 'e', '-', 'l', 'i', 'n', 'u', 'x', '-', 'g', 'n', 'u', 'e', 'a', 'b', 'i', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'i', 'm', 'a', 'g', 'e', '/', '1', '.', '0', '-', 'r', '0', '/', 'd', 'e', 'p', 'l', 'o', 'y', '-', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'i', 'm', 'a', 'g', 'e', '-', 'i', 'm', 'a', 'g', 'e', '-', 'c', 'o', 'm', 'p', 'l', 'e', 't', 'e'], result=['${', 'MACHINE/multibox/donate.txt; \techo ', ['"', 'openvision-develop-extralanguage-python2-10.2-r312-multibox_usb.zip', '"'], ' > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/unforce_multibox.txt; \techo ', ['"', 'Rename the unforce_multibox.txt to force_multibox.txt and move it to the root of your usb-stick', '"'], ' > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/force_multibox_READ.ME; \techo ', ['"', 'When you enter the recovery menu then it will force to install the image openvision-develop-extralanguage-python2-10.2-r312-multibox_usb.zip in the linux1 selection', '"'], ''], eof=True):
                 
    >        pos, closed = parsefunc(buf, result, eof)
             return pos, closed
  File "/home/atef/openvision-development-platform/bitbake/lib/bb/pysh/pyshlex.py", line 234, in WordLexer._parse_parameter(buf=[' ', '>', '>', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'f', 'o', 'r', 'c', 'e', '_', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'R', 'E', 'A', 'D', '.', 'M', 'E', ';', ' ', '\t', 'c', 'd', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', ';', ' ', '\t', 'z', 'i', 'p', ' ', '-', 'r', ' ', '.', '.', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', '-', 'e', 'x', 't', 'r', 'a', 'l', 'a', 'n', 'g', 'u', 'a', 'g', 'e', '-', 'p', 'y', 't', 'h', 'o', 'n', '2', '-', '1', '0', '.', '2', '-', 'r', '3', '1', '2', '-', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '_', 'u', 's', 'b', '.', 'z', 'i', 'p', ' ', '*', ';', ' ', '\t', 'c', 'd', ' ', '.', '.', ';', ' ', '\t', 'r', 'm', ' ', '-', 'R', 'f', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'd', 'e', 'p', 'l', 'o', 'y', '/', 'i', 'm', 'a', 'g', 'e', 's', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', ';', ' ', '\t', '\n', '\t', 'c', 'd', ' ', '/', 'h', 'o', 'm', 'e', '/', 'a', 't', 'e', 'f', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'd', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '-', 'p', 'l', 'a', 't', 'f', 'o', 'r', 'm', '/', 'b', 'u', 'i', 'l', 'd', '/', 't', 'm', 'p', '/', 'w', 'o', 'r', 'k', '/', 'm', 'u', 'l', 't', 'i', 'b', 'o', 'x', '-', 'o', 'e', '-', 'l', 'i', 'n', 'u', 'x', '-', 'g', 'n', 'u', 'e', 'a', 'b', 'i', '/', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'i', 'm', 'a', 'g', 'e', '/', '1', '.', '0', '-', 'r', '0', '/', 'd', 'e', 'p', 'l', 'o', 'y', '-', 'o', 'p', 'e', 'n', 'v', 'i', 's', 'i', 'o', 'n', '-', 'i', 'm', 'a', 'g', 'e', '-', 'i', 'm', 'a', 'g', 'e', '-', 'c', 'o', 'm', 'p', 'l', 'e', 't', 'e'], result=['${', 'MACHINE/multibox/donate.txt; \techo ', ['"', 'openvision-develop-extralanguage-python2-10.2-r312-multibox_usb.zip', '"'], ' > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/unforce_multibox.txt; \techo ', ['"', 'Rename the unforce_multibox.txt to force_multibox.txt and move it to the root of your usb-stick', '"'], ' > /home/atef/openvision-development-platform/build/tmp/deploy/images/multibox/multibox/multibox/force_multibox_READ.ME; \techo ', ['"', 'When you enter the recovery menu then it will force to install the image openvision-develop-extralanguage-python2-10.2-r312-multibox_usb.zip in the linux1 selection', '"'], ''], eof=True):
             if pos==-1:
    >            raise NeedMore()
                 
bb.pysh.pyshlex.NeedMore

Summary: There were 3 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:100: image] Error 1

Done, the compiled image is in build/tmp/deploy/images/multibox folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r312-multibox.zip
atef@ganm:~/openvision-development-platform$ 
`

**Comment by persianpros** [comment]
Answered in forum.
